server:
  port: 8098
  forward-headers-strategy: framework
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: nsight-etc-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  profiles:
    active: local
  datasource:
    url: jdbc:h2:file:./data/etc/tx-io-meta;MODE=Oracle;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  transaction:
    default-timeout: 10
  jackson:
    time-zone: Asia/Seoul
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 5
    jdbc-type-for-null: NULL
    call-setters-on-nulls: true
    default-fetch-size: 500
    cache-enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,threaddump
  endpoint:
    health:
      probes:
        enabled: true

nsight:
  module:
    system-id: NSIGHT-MP
    business-code: ET
    ap-id: local-et-ap01
  timeout:
    online-transaction-seconds: 10
    db-query-seconds: 5
  etc:
    record-enabled: true
