CREATE TABLE IF NOT EXISTS TX_IO_LOG (
    LOG_ID VARCHAR(64) NOT NULL,
    GUID VARCHAR(64) NOT NULL,
    TRACE_ID VARCHAR(64),
    BUSINESS_CODE VARCHAR(10),
    SERVICE_ID VARCHAR(100),
    TRANSACTION_CODE VARCHAR(50),
    SYSTEM_DATE VARCHAR(8),
    RESULT_STATUS VARCHAR(20),
    RESULT_CODE VARCHAR(20),
    ERROR_CODE VARCHAR(50),
    ELAPSED_TIME_MS BIGINT,
    RECORD_TIME VARCHAR(14) NOT NULL,
    IN_SYSTEM_ID VARCHAR(50),
    IN_BUSINESS_CODE VARCHAR(10),
    IN_SERVICE_ID VARCHAR(100),
    IN_TRANSACTION_CODE VARCHAR(50),
    IN_PROCESSING_TYPE VARCHAR(20),
    IN_GUID VARCHAR(64),
    IN_TRACE_ID VARCHAR(64),
    IN_CHANNEL_ID VARCHAR(20),
    IN_USER_ID VARCHAR(50),
    IN_BRANCH_ID VARCHAR(20),
    IN_CENTER_ID VARCHAR(20),
    IN_CLIENT_IP VARCHAR(50),
    IN_REQUEST_TIME VARCHAR(40),
    IN_RESPONSE_TIME VARCHAR(40),
    IN_TRANSACTION_INTIME VARCHAR(40),
    IN_TRANSACTION_OUTTIME VARCHAR(40),
    IN_SYSTEM_DATE VARCHAR(8),
    IN_BIZ_DATE VARCHAR(8),
    IN_AP_ID VARCHAR(50),
    OUT_SYSTEM_ID VARCHAR(50),
    OUT_BUSINESS_CODE VARCHAR(10),
    OUT_SERVICE_ID VARCHAR(100),
    OUT_TRANSACTION_CODE VARCHAR(50),
    OUT_PROCESSING_TYPE VARCHAR(20),
    OUT_GUID VARCHAR(64),
    OUT_TRACE_ID VARCHAR(64),
    OUT_CHANNEL_ID VARCHAR(20),
    OUT_USER_ID VARCHAR(50),
    OUT_BRANCH_ID VARCHAR(20),
    OUT_CENTER_ID VARCHAR(20),
    OUT_CLIENT_IP VARCHAR(50),
    OUT_REQUEST_TIME VARCHAR(40),
    OUT_RESPONSE_TIME VARCHAR(40),
    OUT_TRANSACTION_INTIME VARCHAR(40),
    OUT_TRANSACTION_OUTTIME VARCHAR(40),
    OUT_SYSTEM_DATE VARCHAR(8),
    OUT_BIZ_DATE VARCHAR(8),
    OUT_AP_ID VARCHAR(50),
    PRIMARY KEY (LOG_ID)
);

CREATE INDEX IF NOT EXISTS IDX_TX_IO_GUID ON TX_IO_LOG (GUID, RECORD_TIME DESC);
CREATE INDEX IF NOT EXISTS IDX_TX_IO_TRACE ON TX_IO_LOG (TRACE_ID, RECORD_TIME DESC);
CREATE INDEX IF NOT EXISTS IDX_TX_IO_BIZ ON TX_IO_LOG (BUSINESS_CODE, SYSTEM_DATE DESC, RECORD_TIME DESC);

CREATE TABLE IF NOT EXISTS SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES LONGVARBINARY NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
