CREATE TABLE IF NOT EXISTS UD_FILE (
    FILE_ID VARCHAR(64) NOT NULL,
    ORIGINAL_NAME VARCHAR(500) NOT NULL,
    STORED_PATH VARCHAR(1000) NOT NULL,
    CONTENT_TYPE VARCHAR(200),
    FILE_SIZE BIGINT NOT NULL,
    UPLOAD_USER VARCHAR(100),
    UPLOAD_TIME VARCHAR(14) NOT NULL,
    BUSINESS_CODE VARCHAR(10) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    PRIMARY KEY (FILE_ID)
);

CREATE INDEX IF NOT EXISTS IDX_UD_FILE_BIZ ON UD_FILE (BUSINESS_CODE, UPLOAD_TIME DESC);
